FROM node:carbon-stretch

WORKDIR /app

COPY renderer .
COPY scripts/wait-for /usr/bin

RUN apt-get update
RUN apt-get install -y xvfb ffmpeg libgconf-2-4 libnss3

ENV NODE_ENV=production
RUN yarn install

CMD [ "wait-for", "rabbitmq:5672", "--", "yarn", "start" ]
