FROM node:carbon-alpine

# bash for wait-for
RUN apk add --update bash

WORKDIR /app
COPY scripts/wait-for /usr/bin

EXPOSE 4000

CMD [ "wait-for", "db:27017", "rabbitmq:5672", "--", "yarn", "dev:first-run" ]
