FROM node:carbon-alpine

# bash for wait-for
RUN apk add --update bash

WORKDIR /app
COPY api .
COPY scripts/wait-for /usr/bin

ENV NODE_ENV=production
RUN yarn install

EXPOSE 4000

CMD [ "wait-for", "db:27017", "rabbitmq:5672", "--", "yarn", "start" ]
