FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install git build-essential libsqlite3-dev zlib1g-dev

# build tippecanoe
RUN mkdir -p /tmp/tippecanoe-src
RUN git clone https://github.com/mapbox/tippecanoe.git /tmp/tippecanoe-src
WORKDIR /tmp/tippecanoe-src
RUN make && make install

# clean up after build
WORKDIR /
RUN rm -rf /tmp/tippecanoe-src
RUN apt-get -y remove --purge build-essential && apt-get -y autoremove

# test
CMD tippecanoe --help
