module.exports = {
  CHANGE_INTERVAL: "CHANGE_INTERVAL",
  SET_DATES: "SET_DATES",
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
  SET_COORDINATES: "SET_COORDINATES",
  TOGGLE_PLAY: "TOGGLE_PLAY",

  SET_MAP_BACKGROUND: "SET_MAP_BACKGROUND",
  SET_FEATURE_STYLE: "SET_FEATURE_STYLE",

  SHOW_EXPORT_MENU: "SHOW_EXPORT_MENU",
  HIDE_EXPORT_MENU: "HIDE_EXPORT_MENU",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR"
};
