module.exports = {
  CHANGE_INTERVAL: "CHANGE_INTERVAL",
  SET_DATES: "SET_DATES",
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
  SET_COORDINATES: "SET_COORDINATES",
  TOGGLE_PLAY: "TOGGLE_PLAY",

  SET_MAP_BACKGROUND: "SET_MAP_BACKGROUND",
  SET_FEATURE_STYLE: "SET_FEATURE_STYLE",

  SHOW_EXPORT_MENU: "SHOW_EXPORT_MENU",
  HIDE_EXPORT_MENU: "HIDE_EXPORT_MENU",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

  SET_METADATA: "SET_METADATA",

  EXPORT_DATA_FETCHING: "EXPORT_DATA_FETCHING",
  EXPORT_DATA_FETCHED: "EXPORT_DATA_FETCHED",
  EXPORT_DATA_SAVING: "EXPORT_DATA_SAVING",
  EXPORT_DATA_SAVED: "EXPORT_DATA_SAVED",
  SET_APP_READY: "SET_APP_READY"
};
